name: S3 Backup

on:
  push:
    branches:
      - main
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          
      - name: Archive repository
        run: |
          git archive --format=tar.gz --output=backup.tar.gz HEAD
      - name: Upload to S3
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp backup.tar.gz s3://$AWS_S3_BUCKET/ --region $AWS_REGION
